name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: BigWigsMods/packager@v2
        with:
          args: -g classic_era
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          CURSEFORGE_PROJECT_ID: 1493039
